// کوئری جدید — ضریب وصولی واقعی (جایگزین تدریجی اکسل‌های آفلاین با داده‌ی دیتابیس).
// فرمول طبق تعریف کاربر: ضریب وصولی = مبلغ وصولی (با شرط کارتابلی) ÷ تعداد شماره‌ی یکتای
// پاسخ‌داده‌شده (از داده‌ی VOIP).
// - مبلغ وصولی کارتابلی: از dbo.SaleR_54، ماه از روی _SourceFile استخراج می‌شود (فرمت فایل
//   شامل تاریخ جلالی دوره است: مثلاً "..._SaleR_14030101000000_...").
// - تعداد شماره‌ی یکتای پاسخ‌داده: از dbo.VP_54 (جدول خام VOIP)، فقط ردیف‌هایی که
//   [وضعیت تماس] = 'پاسخ داده'، شمارش DISTINCT روی [موبایل]. ماه از [زمان ایجاد تماس]
//   استخراج می‌شود (متن جلالی، فرمت YYYY/MM/DD).
// نکته‌ی مهم: داده‌ی VOIP فقط از تیر ۱۴۰۵ به بعد در دیتابیس موجود است (بررسی مستقیم با
// sqlcmd)، در حالی که مبلغ وصولی از فروردین ۱۴۰۳ موجوده. یعنی برای ماه‌های قبل از تیر ۱۴۰۵،
// ستون «تعداد شماره یکتای پاسخ‌داده» و «ضریب وصولی» خالی (null) می‌مونه — چون داده‌ای برای
// محاسبه‌شون نیست، نه به‌خاطر باگ. هر وقت داده‌ی VOIP بیشتری وارد دیتابیس بشه، این کوئری
// خودکار همون ماه‌ها رو هم پر می‌کنه.

let
    Source = Sql.Database("127.0.0.1", "Mitra_sarkhosh", [Query="
WITH Vosool AS (
    SELECT
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 7, 4) AS [سال],
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 11, 2) AS [ایندکس ماه],
        SUM([مبلغ وصولی کارتابلی]) AS [مبلغ وصولی کارتابلی]
    FROM dbo.SaleR_54
    GROUP BY
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 7, 4),
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 11, 2)
),
VoipAnswered AS (
    SELECT
        SUBSTRING([زمان ایجاد تماس], 1, 4) AS [سال],
        SUBSTRING([زمان ایجاد تماس], 6, 2) AS [ایندکس ماه],
        COUNT(DISTINCT [موبایل]) AS [تعداد شماره یکتای پاسخ داده]
    FROM dbo.VP_54
    WHERE [وضعیت تماس] = N'پاسخ داده'
    GROUP BY
        SUBSTRING([زمان ایجاد تماس], 1, 4),
        SUBSTRING([زمان ایجاد تماس], 6, 2)
)
SELECT
    v.[سال],
    v.[ایندکس ماه],
    v.[مبلغ وصولی کارتابلی],
    a.[تعداد شماره یکتای پاسخ داده],
    CASE WHEN a.[تعداد شماره یکتای پاسخ داده] > 0
         THEN v.[مبلغ وصولی کارتابلی] / a.[تعداد شماره یکتای پاسخ داده]
         ELSE NULL END AS [ضریب وصولی]
FROM Vosool v
LEFT JOIN VoipAnswered a ON v.[سال] = a.[سال] AND v.[ایندکس ماه] = a.[ایندکس ماه]
ORDER BY v.[سال], v.[ایندکس ماه];
"]),
    #"Changed Type" = Table.TransformColumnTypes(Source, {{"سال", Int64.Type}, {"ایندکس ماه", Int64.Type}, {"مبلغ وصولی کارتابلی", type number}, {"تعداد شماره یکتای پاسخ داده", Int64.Type}, {"ضریب وصولی", type number}}),
    #"Added ماه" = Table.AddColumn(#"Changed Type", "ماه", each {"فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"}{[ایندکس ماه] - 1}, type text)
in
    #"Added ماه"
