// کوئری جدید — «ضریب وصولی» و «پاسخ داد» به تفکیک هر کارشناس، از dbo.SaleR_54
// (نه از پنل SPK — SPK فقط کارمندهای فعال فعلی رو نشون می‌ده و کارمندهای سابق ازش
// حذف می‌شن؛ SaleR_54 یک آرشیو روزانه‌ی واقعیه، پس کارمندهای سابق هم توش می‌مونن).
//
// فرمول‌ها طبق تعریف کاربر (۲۰۲۶-۰۹-۲۹):
// - ضریب وصولی = مبلغ وصولی کارتابلی ÷ تعداد پاسخ داد کارتابلی
// - تعداد پاسخ داد کل      = SUM([تماس - پاسخ داده])       (وضعیت کلی تماس‌ها)
// - تعداد پاسخ داد کارتابلی = SUM([تعداد شماره جواب داده])   (مخرج فرمول ضریب وصولی)
//
// وضعیت فعال/غیرفعال هر کارشناس: از آخرین ردیف موجودش (بر اساس _SourceFile) گرفته
// می‌شه، نه این‌که قاطی GROUP BY بشه — چون این وضعیت روز‌به‌روز عوض می‌شه و می‌خوایم
// همیشه «آخرین وضعیت شناخته‌شده» رو نشون بدیم، نه وضعیت اون روز خاص.
//
// ستون سال_ماه (مثل 140505) از ضرب عددی ساخته می‌شه (سال*100+ماه)، نه چسبوندن متنی،
// چون چسبوندن متنی برای ماه‌های ۱ تا ۹ صفر ابتدایی رو گم می‌کرد.

let
    Source = Sql.Database("127.0.0.1", "Mitra_sarkhosh", [Query="
WITH Agg AS (
    SELECT
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 7, 4) AS [سال],
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 11, 2) AS [ایندکس ماه],
        [کد پرسنلی],
        [نام فروشنده] AS [کارشناس],
        [برچسب فروشنده],
        [سیستم فروش],
        [گروه],
        [سرپرستان] AS [سرپرست],
        [سوپروایزران] AS [سوپروایزر],
        [مدیر],
        SUM([تماس - پاسخ داده]) AS [تعداد پاسخ داد کل],
        SUM([تعداد شماره جواب داده]) AS [تعداد پاسخ داد کارتابلی],
        SUM([تعداد شماره دریافتی]) AS [تعداد شماره دریافتی],
        SUM([فاکتور کارتابلی (تعداد)]) AS [تعداد فاکتور کارتابلی],
        SUM([فاکتور کارتابلی (مبلغ)]) AS [مبلغ فاکتور کارتابلی],
        SUM([جمع مبلغ فاکتور]) AS [جمع مبلغ فاکتور],
        SUM([تعداد وصولی کارتابلی]) AS [تعداد فاکتور وصولی کارتابلی],
        SUM([تعداد وصولی کلی]) AS [تعداد فاکتور وصولی کلی],
        SUM([مبلغ وصولی کارتابلی]) AS [مبلغ وصولی کارتابلی],
        SUM([مبلغ وصولی کلی]) AS [مبلغ وصولی کل],
        AVG([درصد خرید]) AS [درصد خرید]
    FROM dbo.SaleR_54
    GROUP BY
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 7, 4),
        SUBSTRING(_SourceFile, CHARINDEX('_SaleR_', _SourceFile) + 11, 2),
        [کد پرسنلی], [نام فروشنده], [برچسب فروشنده], [سیستم فروش], [گروه], [سرپرستان], [سوپروایزران], [مدیر]
),
LatestStatus AS (
    SELECT [کد پرسنلی], [وضعیت فروشنده],
           ROW_NUMBER() OVER (PARTITION BY [کد پرسنلی] ORDER BY _SourceFile DESC) AS rn
    FROM dbo.SaleR_54
)
SELECT
    a.*,
    CASE WHEN a.[تعداد پاسخ داد کارتابلی] > 0
         THEN a.[مبلغ وصولی کارتابلی] / a.[تعداد پاسخ داد کارتابلی]
         ELSE NULL END AS [ضریب وصولی],
    s.[وضعیت فروشنده] AS [وضعیت کارشناس]
FROM Agg a
LEFT JOIN LatestStatus s ON a.[کد پرسنلی] = s.[کد پرسنلی] AND s.rn = 1
ORDER BY a.[سال], a.[ایندکس ماه];
"]),
    #"Changed Type" = Table.TransformColumnTypes(Source, {{"سال", Int64.Type}, {"ایندکس ماه", Int64.Type}, {"تعداد پاسخ داد کل", Int64.Type}, {"تعداد پاسخ داد کارتابلی", Int64.Type}, {"تعداد شماره دریافتی", Int64.Type}, {"تعداد فاکتور کارتابلی", Int64.Type}, {"مبلغ فاکتور کارتابلی", type number}, {"جمع مبلغ فاکتور", type number}, {"تعداد فاکتور وصولی کارتابلی", Int64.Type}, {"تعداد فاکتور وصولی کلی", Int64.Type}, {"مبلغ وصولی کارتابلی", type number}, {"مبلغ وصولی کل", type number}, {"درصد خرید", type number}, {"ضریب وصولی", type number}}),
    #"Added سال_ماه" = Table.AddColumn(#"Changed Type", "سال_ماه", each [سال] * 100 + [ایندکس ماه], Int64.Type),
    #"Added ماه" = Table.AddColumn(#"Added سال_ماه", "ماه", each {"فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"}{[ایندکس ماه] - 1}, type text)
in
    #"Added ماه"
